- id: doi:10.1371/journal.pone.0238852
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_01.png
- id: doi:10.1007/s10620-020-06482-1
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_02.png
- id: doi:10.1038/s41598-018-30799-7
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_03.png
- id: doi:10.1111/nyas.13157
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_04.png
- id: doi:10.1111/nyas.13151
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_05.png
- id: doi:10.1111/nyas.13109
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_06.png
- id: doi:10.1371/journal.pone.0153185
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_07.png
- id: doi:10.1152/ajpgi.00333.2014
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_08.png
- id: doi:10.3791/52215
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_09.png
- id: doi:10.1016/j.trsl.2014.03.007
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_10.png
- id: doi:10.1038/ajg.2013.289
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_11.png
- id: doi:10.1152/ajpgi.00486.2012
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_12.png
- id: doi:10.1152/ajpgi.00225.2012
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_13.png
- id: doi:10.3791/4100
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_14.png
- id: doi:10.1007/s00464-012-2350-0
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_15.png
- id: doi:10.1038/485181a
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_16.png
- id: doi:10.3389/fimmu.2012.00107
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_17.png
- id: doi:10.1016/j.trsl.2010.06.003
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_18.png
- id: doi:10.1172/JCI40676
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_19.png
- id: pmid:15503887
  image: https://raw.githubusercontent.com/ShakerLab/shakerlab.github.io/main/images/thumbnails/thumb_20.png
